package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1



/**
 * Aceites generated by hbm2java
 */
public class Aceites  implements java.io.Serializable {


     private Integer id;
     private RequerimientoExpress requerimientoExpress;
     private String typeAceite;
     private String descripcion;
     private Double montoAceite;
     private Integer idTallerExpress;

    public Aceites() {
    }

	
    public Aceites(RequerimientoExpress requerimientoExpress) {
        this.requerimientoExpress = requerimientoExpress;
    }
    public Aceites(RequerimientoExpress requerimientoExpress, String typeAceite, String descripcion, Double montoAceite, Integer idTallerExpress) {
       this.requerimientoExpress = requerimientoExpress;
       this.typeAceite = typeAceite;
       this.descripcion = descripcion;
       this.montoAceite = montoAceite;
       this.idTallerExpress = idTallerExpress;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RequerimientoExpress getRequerimientoExpress() {
        return this.requerimientoExpress;
    }
    
    public void setRequerimientoExpress(RequerimientoExpress requerimientoExpress) {
        this.requerimientoExpress = requerimientoExpress;
    }
    public String getTypeAceite() {
        return this.typeAceite;
    }
    
    public void setTypeAceite(String typeAceite) {
        this.typeAceite = typeAceite;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getMontoAceite() {
        return this.montoAceite;
    }
    
    public void setMontoAceite(Double montoAceite) {
        this.montoAceite = montoAceite;
    }
    public Integer getIdTallerExpress() {
        return this.idTallerExpress;
    }
    
    public void setIdTallerExpress(Integer idTallerExpress) {
        this.idTallerExpress = idTallerExpress;
    }




}


