package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Autorizacion generated by hbm2java
 */
public class Autorizacion  implements java.io.Serializable {


     private Integer id;
     private Bitacora bitacora;
     private Client client;
     private Date fechaAuto;
     private String estado;
     private Integer idClient;

    public Autorizacion() {
    }

	
    public Autorizacion(Bitacora bitacora, Client client) {
        this.bitacora = bitacora;
        this.client = client;
    }
    public Autorizacion(Bitacora bitacora, Client client, Date fechaAuto, String estado, Integer idClient) {
       this.bitacora = bitacora;
       this.client = client;
       this.fechaAuto = fechaAuto;
       this.estado = estado;
       this.idClient = idClient;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bitacora getBitacora() {
        return this.bitacora;
    }
    
    public void setBitacora(Bitacora bitacora) {
        this.bitacora = bitacora;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getFechaAuto() {
        return this.fechaAuto;
    }
    
    public void setFechaAuto(Date fechaAuto) {
        this.fechaAuto = fechaAuto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }




}


