package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Automovil generated by hbm2java
 */
public class Automovil  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private String placa;
     private String color;
     private String modelo;
     private Date annio;
     private String typeVehiculo;
     private Integer idClient;
     private Set<RequerimientoGeneral> requerimientoGenerals = new HashSet<RequerimientoGeneral>(0);
     private Set<RequerimientoEnderezadoPintura> requerimientoEnderezadoPinturas = new HashSet<RequerimientoEnderezadoPintura>(0);
     private Set<RequerimientoExpress> requerimientoExpresses = new HashSet<RequerimientoExpress>(0);
     private Set<Fotos> fotoses = new HashSet<Fotos>(0);

    public Automovil() {
    }

	
    public Automovil(Client client) {
        this.client = client;
    }
    public Automovil(Client client, String placa, String color, String modelo, Date annio, String typeVehiculo, Integer idClient, Set<RequerimientoGeneral> requerimientoGenerals, Set<RequerimientoEnderezadoPintura> requerimientoEnderezadoPinturas, Set<RequerimientoExpress> requerimientoExpresses, Set<Fotos> fotoses) {
       this.client = client;
       this.placa = placa;
       this.color = color;
       this.modelo = modelo;
       this.annio = annio;
       this.typeVehiculo = typeVehiculo;
       this.idClient = idClient;
       this.requerimientoGenerals = requerimientoGenerals;
       this.requerimientoEnderezadoPinturas = requerimientoEnderezadoPinturas;
       this.requerimientoExpresses = requerimientoExpresses;
       this.fotoses = fotoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Date getAnnio() {
        return this.annio;
    }
    
    public void setAnnio(Date annio) {
        this.annio = annio;
    }
    public String getTypeVehiculo() {
        return this.typeVehiculo;
    }
    
    public void setTypeVehiculo(String typeVehiculo) {
        this.typeVehiculo = typeVehiculo;
    }
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public Set<RequerimientoGeneral> getRequerimientoGenerals() {
        return this.requerimientoGenerals;
    }
    
    public void setRequerimientoGenerals(Set<RequerimientoGeneral> requerimientoGenerals) {
        this.requerimientoGenerals = requerimientoGenerals;
    }
    public Set<RequerimientoEnderezadoPintura> getRequerimientoEnderezadoPinturas() {
        return this.requerimientoEnderezadoPinturas;
    }
    
    public void setRequerimientoEnderezadoPinturas(Set<RequerimientoEnderezadoPintura> requerimientoEnderezadoPinturas) {
        this.requerimientoEnderezadoPinturas = requerimientoEnderezadoPinturas;
    }
    public Set<RequerimientoExpress> getRequerimientoExpresses() {
        return this.requerimientoExpresses;
    }
    
    public void setRequerimientoExpresses(Set<RequerimientoExpress> requerimientoExpresses) {
        this.requerimientoExpresses = requerimientoExpresses;
    }
    public Set<Fotos> getFotoses() {
        return this.fotoses;
    }
    
    public void setFotoses(Set<Fotos> fotoses) {
        this.fotoses = fotoses;
    }




}


