package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private Integer id;
     private RequerimientoEnderezadoPintura requerimientoEnderezadoPintura;
     private RequerimientoExpress requerimientoExpress;
     private RequerimientoGeneral requerimientoGeneral;
     private String descripcion;
     private Date fecha;
     private Integer idTallerExpress;
     private Integer idTallerGeneral;
     private Integer idPinturaenderezado;
     private Integer idAutorizacion;
     private Set<Fotos> fotoses = new HashSet<Fotos>(0);
     private Set<Autorizacion> autorizacions = new HashSet<Autorizacion>(0);

    public Bitacora() {
    }

	
    public Bitacora(RequerimientoEnderezadoPintura requerimientoEnderezadoPintura, RequerimientoExpress requerimientoExpress, RequerimientoGeneral requerimientoGeneral) {
        this.requerimientoEnderezadoPintura = requerimientoEnderezadoPintura;
        this.requerimientoExpress = requerimientoExpress;
        this.requerimientoGeneral = requerimientoGeneral;
    }
    public Bitacora(RequerimientoEnderezadoPintura requerimientoEnderezadoPintura, RequerimientoExpress requerimientoExpress, RequerimientoGeneral requerimientoGeneral, String descripcion, Date fecha, Integer idTallerExpress, Integer idTallerGeneral, Integer idPinturaenderezado, Integer idAutorizacion, Set<Fotos> fotoses, Set<Autorizacion> autorizacions) {
       this.requerimientoEnderezadoPintura = requerimientoEnderezadoPintura;
       this.requerimientoExpress = requerimientoExpress;
       this.requerimientoGeneral = requerimientoGeneral;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.idTallerExpress = idTallerExpress;
       this.idTallerGeneral = idTallerGeneral;
       this.idPinturaenderezado = idPinturaenderezado;
       this.idAutorizacion = idAutorizacion;
       this.fotoses = fotoses;
       this.autorizacions = autorizacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RequerimientoEnderezadoPintura getRequerimientoEnderezadoPintura() {
        return this.requerimientoEnderezadoPintura;
    }
    
    public void setRequerimientoEnderezadoPintura(RequerimientoEnderezadoPintura requerimientoEnderezadoPintura) {
        this.requerimientoEnderezadoPintura = requerimientoEnderezadoPintura;
    }
    public RequerimientoExpress getRequerimientoExpress() {
        return this.requerimientoExpress;
    }
    
    public void setRequerimientoExpress(RequerimientoExpress requerimientoExpress) {
        this.requerimientoExpress = requerimientoExpress;
    }
    public RequerimientoGeneral getRequerimientoGeneral() {
        return this.requerimientoGeneral;
    }
    
    public void setRequerimientoGeneral(RequerimientoGeneral requerimientoGeneral) {
        this.requerimientoGeneral = requerimientoGeneral;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getIdTallerExpress() {
        return this.idTallerExpress;
    }
    
    public void setIdTallerExpress(Integer idTallerExpress) {
        this.idTallerExpress = idTallerExpress;
    }
    public Integer getIdTallerGeneral() {
        return this.idTallerGeneral;
    }
    
    public void setIdTallerGeneral(Integer idTallerGeneral) {
        this.idTallerGeneral = idTallerGeneral;
    }
    public Integer getIdPinturaenderezado() {
        return this.idPinturaenderezado;
    }
    
    public void setIdPinturaenderezado(Integer idPinturaenderezado) {
        this.idPinturaenderezado = idPinturaenderezado;
    }
    public Integer getIdAutorizacion() {
        return this.idAutorizacion;
    }
    
    public void setIdAutorizacion(Integer idAutorizacion) {
        this.idAutorizacion = idAutorizacion;
    }
    public Set<Fotos> getFotoses() {
        return this.fotoses;
    }
    
    public void setFotoses(Set<Fotos> fotoses) {
        this.fotoses = fotoses;
    }
    public Set<Autorizacion> getAutorizacions() {
        return this.autorizacions;
    }
    
    public void setAutorizacions(Set<Autorizacion> autorizacions) {
        this.autorizacions = autorizacions;
    }




}


