package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1



/**
 * Filtro generated by hbm2java
 */
public class Filtro  implements java.io.Serializable {


     private Integer id;
     private RequerimientoExpress requerimientoExpress;
     private String typeFiltro;
     private String descripcion;
     private Double montoFiltro;
     private Integer idTallerExpress;

    public Filtro() {
    }

	
    public Filtro(RequerimientoExpress requerimientoExpress) {
        this.requerimientoExpress = requerimientoExpress;
    }
    public Filtro(RequerimientoExpress requerimientoExpress, String typeFiltro, String descripcion, Double montoFiltro, Integer idTallerExpress) {
       this.requerimientoExpress = requerimientoExpress;
       this.typeFiltro = typeFiltro;
       this.descripcion = descripcion;
       this.montoFiltro = montoFiltro;
       this.idTallerExpress = idTallerExpress;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RequerimientoExpress getRequerimientoExpress() {
        return this.requerimientoExpress;
    }
    
    public void setRequerimientoExpress(RequerimientoExpress requerimientoExpress) {
        this.requerimientoExpress = requerimientoExpress;
    }
    public String getTypeFiltro() {
        return this.typeFiltro;
    }
    
    public void setTypeFiltro(String typeFiltro) {
        this.typeFiltro = typeFiltro;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getMontoFiltro() {
        return this.montoFiltro;
    }
    
    public void setMontoFiltro(Double montoFiltro) {
        this.montoFiltro = montoFiltro;
    }
    public Integer getIdTallerExpress() {
        return this.idTallerExpress;
    }
    
    public void setIdTallerExpress(Integer idTallerExpress) {
        this.idTallerExpress = idTallerExpress;
    }




}


