package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Fotos generated by hbm2java
 */
public class Fotos  implements java.io.Serializable {


     private Integer id;
     private Automovil automovil;
     private Bitacora bitacora;
     private String descripcion;
     private Date fechaFoto;
     private Integer idAutomovil;
     private String idBitacora;

    public Fotos() {
    }

	
    public Fotos(Automovil automovil, Bitacora bitacora, String idBitacora) {
        this.automovil = automovil;
        this.bitacora = bitacora;
        this.idBitacora = idBitacora;
    }
    public Fotos(Automovil automovil, Bitacora bitacora, String descripcion, Date fechaFoto, Integer idAutomovil, String idBitacora) {
       this.automovil = automovil;
       this.bitacora = bitacora;
       this.descripcion = descripcion;
       this.fechaFoto = fechaFoto;
       this.idAutomovil = idAutomovil;
       this.idBitacora = idBitacora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Automovil getAutomovil() {
        return this.automovil;
    }
    
    public void setAutomovil(Automovil automovil) {
        this.automovil = automovil;
    }
    public Bitacora getBitacora() {
        return this.bitacora;
    }
    
    public void setBitacora(Bitacora bitacora) {
        this.bitacora = bitacora;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaFoto() {
        return this.fechaFoto;
    }
    
    public void setFechaFoto(Date fechaFoto) {
        this.fechaFoto = fechaFoto;
    }
    public Integer getIdAutomovil() {
        return this.idAutomovil;
    }
    
    public void setIdAutomovil(Integer idAutomovil) {
        this.idAutomovil = idAutomovil;
    }
    public String getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(String idBitacora) {
        this.idBitacora = idBitacora;
    }




}


