package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1



/**
 * GeneralSystem generated by hbm2java
 */
public class GeneralSystem  implements java.io.Serializable {


     private Integer id;
     private RequerimientoGeneral requerimientoGeneral;
     private String descripcion;
     private String typeGeneral;
     private Double montoGeneralSystem;
     private Integer idGeneral;

    public GeneralSystem() {
    }

	
    public GeneralSystem(RequerimientoGeneral requerimientoGeneral) {
        this.requerimientoGeneral = requerimientoGeneral;
    }
    public GeneralSystem(RequerimientoGeneral requerimientoGeneral, String descripcion, String typeGeneral, Double montoGeneralSystem, Integer idGeneral) {
       this.requerimientoGeneral = requerimientoGeneral;
       this.descripcion = descripcion;
       this.typeGeneral = typeGeneral;
       this.montoGeneralSystem = montoGeneralSystem;
       this.idGeneral = idGeneral;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RequerimientoGeneral getRequerimientoGeneral() {
        return this.requerimientoGeneral;
    }
    
    public void setRequerimientoGeneral(RequerimientoGeneral requerimientoGeneral) {
        this.requerimientoGeneral = requerimientoGeneral;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTypeGeneral() {
        return this.typeGeneral;
    }
    
    public void setTypeGeneral(String typeGeneral) {
        this.typeGeneral = typeGeneral;
    }
    public Double getMontoGeneralSystem() {
        return this.montoGeneralSystem;
    }
    
    public void setMontoGeneralSystem(Double montoGeneralSystem) {
        this.montoGeneralSystem = montoGeneralSystem;
    }
    public Integer getIdGeneral() {
        return this.idGeneral;
    }
    
    public void setIdGeneral(Integer idGeneral) {
        this.idGeneral = idGeneral;
    }




}


