package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mecanico generated by hbm2java
 */
public class Mecanico  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String direction;
     private String phoneNumber;
     private String estatus;
     private Integer edad;
     private Date fechaNac;
     private String correo;
     private Set<RequerimientoEnderezadoPintura> requerimientoEnderezadoPinturas = new HashSet<RequerimientoEnderezadoPintura>(0);
     private Set<RequerimientoExpress> requerimientoExpresses = new HashSet<RequerimientoExpress>(0);
     private Set<RequerimientoGeneral> requerimientoGenerals = new HashSet<RequerimientoGeneral>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Mecanico() {
    }

    public Mecanico(String name, String direction, String phoneNumber, String estatus, Integer edad, Date fechaNac, String correo, Set<RequerimientoEnderezadoPintura> requerimientoEnderezadoPinturas, Set<RequerimientoExpress> requerimientoExpresses, Set<RequerimientoGeneral> requerimientoGenerals, Set<Usuario> usuarios) {
       this.name = name;
       this.direction = direction;
       this.phoneNumber = phoneNumber;
       this.estatus = estatus;
       this.edad = edad;
       this.fechaNac = fechaNac;
       this.correo = correo;
       this.requerimientoEnderezadoPinturas = requerimientoEnderezadoPinturas;
       this.requerimientoExpresses = requerimientoExpresses;
       this.requerimientoGenerals = requerimientoGenerals;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<RequerimientoEnderezadoPintura> getRequerimientoEnderezadoPinturas() {
        return this.requerimientoEnderezadoPinturas;
    }
    
    public void setRequerimientoEnderezadoPinturas(Set<RequerimientoEnderezadoPintura> requerimientoEnderezadoPinturas) {
        this.requerimientoEnderezadoPinturas = requerimientoEnderezadoPinturas;
    }
    public Set<RequerimientoExpress> getRequerimientoExpresses() {
        return this.requerimientoExpresses;
    }
    
    public void setRequerimientoExpresses(Set<RequerimientoExpress> requerimientoExpresses) {
        this.requerimientoExpresses = requerimientoExpresses;
    }
    public Set<RequerimientoGeneral> getRequerimientoGenerals() {
        return this.requerimientoGenerals;
    }
    
    public void setRequerimientoGenerals(Set<RequerimientoGeneral> requerimientoGenerals) {
        this.requerimientoGenerals = requerimientoGenerals;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


