package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1



/**
 * Piezas generated by hbm2java
 */
public class Piezas  implements java.io.Serializable {


     private Integer id;
     private RequerimientoExpress requerimientoExpress;
     private String typePieza;
     private String descripcion;
     private Double montoPiezas;
     private Integer idTallerExpress;

    public Piezas() {
    }

	
    public Piezas(RequerimientoExpress requerimientoExpress) {
        this.requerimientoExpress = requerimientoExpress;
    }
    public Piezas(RequerimientoExpress requerimientoExpress, String typePieza, String descripcion, Double montoPiezas, Integer idTallerExpress) {
       this.requerimientoExpress = requerimientoExpress;
       this.typePieza = typePieza;
       this.descripcion = descripcion;
       this.montoPiezas = montoPiezas;
       this.idTallerExpress = idTallerExpress;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RequerimientoExpress getRequerimientoExpress() {
        return this.requerimientoExpress;
    }
    
    public void setRequerimientoExpress(RequerimientoExpress requerimientoExpress) {
        this.requerimientoExpress = requerimientoExpress;
    }
    public String getTypePieza() {
        return this.typePieza;
    }
    
    public void setTypePieza(String typePieza) {
        this.typePieza = typePieza;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getMontoPiezas() {
        return this.montoPiezas;
    }
    
    public void setMontoPiezas(Double montoPiezas) {
        this.montoPiezas = montoPiezas;
    }
    public Integer getIdTallerExpress() {
        return this.idTallerExpress;
    }
    
    public void setIdTallerExpress(Integer idTallerExpress) {
        this.idTallerExpress = idTallerExpress;
    }




}


