package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1



/**
 * Pintura generated by hbm2java
 */
public class Pintura  implements java.io.Serializable {


     private Integer id;
     private RequerimientoEnderezadoPintura requerimientoEnderezadoPintura;
     private String typeColor;
     private Integer idPinturaenderezado;
     private Double montoColor;

    public Pintura() {
    }

	
    public Pintura(RequerimientoEnderezadoPintura requerimientoEnderezadoPintura) {
        this.requerimientoEnderezadoPintura = requerimientoEnderezadoPintura;
    }
    public Pintura(RequerimientoEnderezadoPintura requerimientoEnderezadoPintura, String typeColor, Integer idPinturaenderezado, Double montoColor) {
       this.requerimientoEnderezadoPintura = requerimientoEnderezadoPintura;
       this.typeColor = typeColor;
       this.idPinturaenderezado = idPinturaenderezado;
       this.montoColor = montoColor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RequerimientoEnderezadoPintura getRequerimientoEnderezadoPintura() {
        return this.requerimientoEnderezadoPintura;
    }
    
    public void setRequerimientoEnderezadoPintura(RequerimientoEnderezadoPintura requerimientoEnderezadoPintura) {
        this.requerimientoEnderezadoPintura = requerimientoEnderezadoPintura;
    }
    public String getTypeColor() {
        return this.typeColor;
    }
    
    public void setTypeColor(String typeColor) {
        this.typeColor = typeColor;
    }
    public Integer getIdPinturaenderezado() {
        return this.idPinturaenderezado;
    }
    
    public void setIdPinturaenderezado(Integer idPinturaenderezado) {
        this.idPinturaenderezado = idPinturaenderezado;
    }
    public Double getMontoColor() {
        return this.montoColor;
    }
    
    public void setMontoColor(Double montoColor) {
        this.montoColor = montoColor;
    }




}


