package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1



/**
 * RecuperarPass generated by hbm2java
 */
public class RecuperarPass  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String recuperarpass;
     private Integer idUsuario;

    public RecuperarPass() {
    }

	
    public RecuperarPass(Usuario usuario) {
        this.usuario = usuario;
    }
    public RecuperarPass(Usuario usuario, String recuperarpass, Integer idUsuario) {
       this.usuario = usuario;
       this.recuperarpass = recuperarpass;
       this.idUsuario = idUsuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRecuperarpass() {
        return this.recuperarpass;
    }
    
    public void setRecuperarpass(String recuperarpass) {
        this.recuperarpass = recuperarpass;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }




}


