package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RequerimientoGeneral generated by hbm2java
 */
public class RequerimientoGeneral  implements java.io.Serializable {


     private Integer id;
     private Automovil automovil;
     private Mecanico mecanico;
     private String descripcion;
     private Date fechaIni;
     private Date fechaFin;
     private Double totalGeneral;
     private Integer idMecanico;
     private Integer idAutomovil;
     private Set<Bitacora> bitacoras = new HashSet<Bitacora>(0);
     private Set<GeneralSystem> generalSystems = new HashSet<GeneralSystem>(0);
     private Set<SistemaElectrico> sistemaElectricos = new HashSet<SistemaElectrico>(0);

    public RequerimientoGeneral() {
    }

	
    public RequerimientoGeneral(Automovil automovil, Mecanico mecanico) {
        this.automovil = automovil;
        this.mecanico = mecanico;
    }
    public RequerimientoGeneral(Automovil automovil, Mecanico mecanico, String descripcion, Date fechaIni, Date fechaFin, Double totalGeneral, Integer idMecanico, Integer idAutomovil, Set<Bitacora> bitacoras, Set<GeneralSystem> generalSystems, Set<SistemaElectrico> sistemaElectricos) {
       this.automovil = automovil;
       this.mecanico = mecanico;
       this.descripcion = descripcion;
       this.fechaIni = fechaIni;
       this.fechaFin = fechaFin;
       this.totalGeneral = totalGeneral;
       this.idMecanico = idMecanico;
       this.idAutomovil = idAutomovil;
       this.bitacoras = bitacoras;
       this.generalSystems = generalSystems;
       this.sistemaElectricos = sistemaElectricos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Automovil getAutomovil() {
        return this.automovil;
    }
    
    public void setAutomovil(Automovil automovil) {
        this.automovil = automovil;
    }
    public Mecanico getMecanico() {
        return this.mecanico;
    }
    
    public void setMecanico(Mecanico mecanico) {
        this.mecanico = mecanico;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Double getTotalGeneral() {
        return this.totalGeneral;
    }
    
    public void setTotalGeneral(Double totalGeneral) {
        this.totalGeneral = totalGeneral;
    }
    public Integer getIdMecanico() {
        return this.idMecanico;
    }
    
    public void setIdMecanico(Integer idMecanico) {
        this.idMecanico = idMecanico;
    }
    public Integer getIdAutomovil() {
        return this.idAutomovil;
    }
    
    public void setIdAutomovil(Integer idAutomovil) {
        this.idAutomovil = idAutomovil;
    }
    public Set<Bitacora> getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set<Bitacora> bitacoras) {
        this.bitacoras = bitacoras;
    }
    public Set<GeneralSystem> getGeneralSystems() {
        return this.generalSystems;
    }
    
    public void setGeneralSystems(Set<GeneralSystem> generalSystems) {
        this.generalSystems = generalSystems;
    }
    public Set<SistemaElectrico> getSistemaElectricos() {
        return this.sistemaElectricos;
    }
    
    public void setSistemaElectricos(Set<SistemaElectrico> sistemaElectricos) {
        this.sistemaElectricos = sistemaElectricos;
    }




}


