package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1



/**
 * SistemaElectrico generated by hbm2java
 */
public class SistemaElectrico  implements java.io.Serializable {


     private Integer id;
     private RequerimientoGeneral requerimientoGeneral;
     private String typeSistema;
     private Double montoElectrico;
     private Integer idTallerGeneral;

    public SistemaElectrico() {
    }

	
    public SistemaElectrico(RequerimientoGeneral requerimientoGeneral) {
        this.requerimientoGeneral = requerimientoGeneral;
    }
    public SistemaElectrico(RequerimientoGeneral requerimientoGeneral, String typeSistema, Double montoElectrico, Integer idTallerGeneral) {
       this.requerimientoGeneral = requerimientoGeneral;
       this.typeSistema = typeSistema;
       this.montoElectrico = montoElectrico;
       this.idTallerGeneral = idTallerGeneral;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RequerimientoGeneral getRequerimientoGeneral() {
        return this.requerimientoGeneral;
    }
    
    public void setRequerimientoGeneral(RequerimientoGeneral requerimientoGeneral) {
        this.requerimientoGeneral = requerimientoGeneral;
    }
    public String getTypeSistema() {
        return this.typeSistema;
    }
    
    public void setTypeSistema(String typeSistema) {
        this.typeSistema = typeSistema;
    }
    public Double getMontoElectrico() {
        return this.montoElectrico;
    }
    
    public void setMontoElectrico(Double montoElectrico) {
        this.montoElectrico = montoElectrico;
    }
    public Integer getIdTallerGeneral() {
        return this.idTallerGeneral;
    }
    
    public void setIdTallerGeneral(Integer idTallerGeneral) {
        this.idTallerGeneral = idTallerGeneral;
    }




}


