package grupo.qq.model;
// Generated 06-19-2018 05:50:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private Mecanico mecanico;
     private Rol rol;
     private String usuario;
     private String password;
     private Integer idRol;
     private Integer idEmployee;
     private Integer idClient;
     private Set<RecuperarPass> recuperarPasses = new HashSet<RecuperarPass>(0);

    public Usuario() {
    }

	
    public Usuario(Client client, Mecanico mecanico, Rol rol) {
        this.client = client;
        this.mecanico = mecanico;
        this.rol = rol;
    }
    public Usuario(Client client, Mecanico mecanico, Rol rol, String usuario, String password, Integer idRol, Integer idEmployee, Integer idClient, Set<RecuperarPass> recuperarPasses) {
       this.client = client;
       this.mecanico = mecanico;
       this.rol = rol;
       this.usuario = usuario;
       this.password = password;
       this.idRol = idRol;
       this.idEmployee = idEmployee;
       this.idClient = idClient;
       this.recuperarPasses = recuperarPasses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Mecanico getMecanico() {
        return this.mecanico;
    }
    
    public void setMecanico(Mecanico mecanico) {
        this.mecanico = mecanico;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public Integer getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(Integer idEmployee) {
        this.idEmployee = idEmployee;
    }
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public Set<RecuperarPass> getRecuperarPasses() {
        return this.recuperarPasses;
    }
    
    public void setRecuperarPasses(Set<RecuperarPass> recuperarPasses) {
        this.recuperarPasses = recuperarPasses;
    }




}


